name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          npm install

      # Шаг 4: Запуск тестов (если они есть)
      - name: Run tests (если есть)
        run: |
          npm test || true  # Если у вас есть тесты, добавьте их сюда

      # Шаг 5: Настройка SSH и деплой на сервер
      - name: Deploy to server
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: 109.196.100.189  # Используем IP-адрес вместо домена
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          # Настройка ssh-agent
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Добавление хоста в known_hosts для предотвращения ошибки при подключении
          ssh-keyscan -H 109.196.100.189 >> ~/.ssh/known_hosts

          # Подключение через SSH и выполнение команд на сервере
          ssh -i ~/.ssh/id_ed25519 $DEPLOY_USER@109.196.100.189 << 'EOF'
            cd /path/to/your/project  # Убедитесь, что путь правильный
            git pull  # Загружаем последние изменения
            npm install  # Устанавливаем зависимости
            pm2 restart all  # Перезапуск приложения через pm2
          EOF
